[DiscordServerInfo]  
;==================================================
; Customer Settings
;==================================================
CustomerName       = 
CustomerHardwareId = 
 
;==================================================
; Settings
;================================================== 
DiscordServerPort    = 55990
DiscordServerODBC    = MuOnlineS6
CaseSensitive        = 0
MD5Encryption        = 0
DiscordServerShowLog = 1

;==================================================
; Bot Settings 
;================================================== 
DiscordBotActive = 1
DiscordBotToken  = 