CREATE TABLE [dbo].[RankingDemonGuardian](
	[Name] [varchar](10) NOT NULL,
	[BossKill] [int] NOT NULL DEFAULT(0),
	[Kills] [int] NOT NULL DEFAULT(0),
	[Deaths] [int] NOT NULL DEFAULT(0),
 CONSTRAINT [PK_RankingDemonGuardian] PRIMARY KEY CLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


